# Generated by Django 4.2.3 on 2023-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='first_name',
            field=models.CharField(default='default title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
