# Generated by Django 4.2.3 on 2023-07-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_5', '0002_advertisement_first_name_alter_advertisement_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='first_name',
        ),
    ]
