# Generated by Django 4.2.3 on 2023-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_5', '0003_remove_advertisement_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
