# Generated by Django 4.2.3 on 2023-08-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_5', '0018_alter_advertisement_image_alter_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
